version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    linear_regression_api:
      image: shramanpadhalni-web/deep-oc-linear_regression_api
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    linear_regression_api-gpu:
      image: shramanpadhalni-web/deep-oc-linear_regression_api:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    linear_regression_api-rclone:
      extends:
        service: linear_regression_api
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
